// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/settings/data/user_document_currency_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kazi/features/settings/domain/models/billing_cycle.dart' as _i6;
import 'package:kazi/features/settings/domain/models/user_settings.dart' as _i2;
import 'package:kazi/features/settings/domain/repositories/user_settings_repository.dart'
    as _i3;
import 'package:kazi_core/kazi_core.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserSettings_0 extends _i1.SmartFake implements _i2.UserSettings {
  _FakeUserSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsRepository extends _i1.Mock
    implements _i3.UserSettingsRepository {
  MockUserSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserSettings> get(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId]),
            returnValue: _i4.Future<_i2.UserSettings>.value(
              _FakeUserSettings_0(this, Invocation.method(#get, [userId])),
            ),
          )
          as _i4.Future<_i2.UserSettings>);

  @override
  _i4.Future<void> setDefaultCurrency(
    String? userId,
    _i5.SupportedCurrency? currency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultCurrency, [userId, currency]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBillingCycle(String? userId, _i6.BillingCycle? cycle) =>
      (super.noSuchMethod(
            Invocation.method(#setBillingCycle, [userId, cycle]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markCurrencyMigrated(
    String? userId, {
    required int? migrated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markCurrencyMigrated,
              [userId],
              {#migrated: migrated},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setProfession(String? userId, String? profession) =>
      (super.noSuchMethod(
            Invocation.method(#setProfession, [userId, profession]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markSetupCompleted(
    String? userId, {
    required bool? essentialsOnly,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markSetupCompleted,
              [userId],
              {#essentialsOnly: essentialsOnly},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markOnboardingStep(String? userId, String? step) =>
      (super.noSuchMethod(
            Invocation.method(#markOnboardingStep, [userId, step]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetOnboardingForDebug(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#resetOnboardingForDebug, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
