include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - '**/*.g.dart'
    - 'lib/app/shared/l10n/generated/'

linter:
  rules:
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_statements: true
    use_colored_box: true
    use_decorated_box: true
    use_key_in_widget_constructors: true
