name: my_services
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.5.2+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.2.1
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  get_it: ^7.2.0
  go_router: ^6.5.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  google_mobile_ads: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.1.7
  fake_cloud_firestore: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/app/shared/l10n/arb
  output_dir: lib/app/shared/l10n/generated
  use_deferred_loading: false
