name: kazi
description: An app to keep track of your personal or work services.
publish_to: 'none'
version: 1.0.4+9

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  intl: ^0.18.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1
  webview_flutter: ^4.4.4

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/app/core/l10n/arb
  output_dir: lib/app/core/l10n/generated
  use_deferred_loading: false
