name: kazi
description: An app to keep track of your personal or work services.
publish_to: 'none'
version: 1.0.4+9

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  app_links: ^6.1.1
  bloc: ^8.1.4
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10
  get_it: ^7.7.0
  go_router: ^14.1.4
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  kazi_core: 
    git:
      url: https://github.com/lucas-242/kazi_core.git
      ref: master
  kazi_design_system: 
    git:
      url: https://github.com/lucas-242/kazi_design_system.git
      ref: master
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated
  use_deferred_loading: false
