name: kazi
description: An app to keep track of your personal or work services.
publish_to: 'none'
version: 1.0.2+5

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.7.1
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: ^2.3.0
  flutter_svg: ^2.0.6
  get_it: ^7.2.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.2
  intl: ^0.18.0
  shared_preferences: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  fake_cloud_firestore: ^2.4.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/app/shared/l10n/arb
  output_dir: lib/app/shared/l10n/generated
  use_deferred_loading: false
