name: kazi
description: An app to keep track of your personal or work services.
publish_to: 'none'
version: 0.10.2+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.0.5
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.4
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  get_it: ^7.2.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.0
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  showcaseview: ^2.0.3

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.1.7
  fake_cloud_firestore: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/app/shared/l10n/arb
  output_dir: lib/app/shared/l10n/generated
  use_deferred_loading: false
