// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/onboarding/presenter/controllers/guided_setup_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kazi/core/services/domain/analytics_event.dart' as _i15;
import 'package:kazi/core/services/domain/analytics_service.dart' as _i14;
import 'package:kazi/core/services/domain/interstitial_ad_service.dart' as _i17;
import 'package:kazi/core/services/domain/time_service.dart' as _i16;
import 'package:kazi/features/auth/domain/models/app_user.dart' as _i13;
import 'package:kazi/features/auth/domain/services/auth_service.dart' as _i12;
import 'package:kazi/features/services/domain/models/service.dart' as _i10;
import 'package:kazi/features/services/domain/models/service_type.dart' as _i3;
import 'package:kazi/features/services/domain/repositories/service_type_repository.dart'
    as _i11;
import 'package:kazi/features/services/domain/repositories/services_repository.dart'
    as _i9;
import 'package:kazi/features/settings/domain/models/billing_cycle.dart' as _i7;
import 'package:kazi/features/settings/domain/models/user_settings.dart' as _i2;
import 'package:kazi/features/settings/domain/repositories/currency_migration_repository.dart'
    as _i8;
import 'package:kazi/features/settings/domain/repositories/user_settings_repository.dart'
    as _i4;
import 'package:kazi_core/kazi_core.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserSettings_0 extends _i1.SmartFake implements _i2.UserSettings {
  _FakeUserSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServiceType_1 extends _i1.SmartFake implements _i3.ServiceType {
  _FakeServiceType_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsRepository extends _i1.Mock
    implements _i4.UserSettingsRepository {
  MockUserSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserSettings> get(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId]),
            returnValue: _i5.Future<_i2.UserSettings>.value(
              _FakeUserSettings_0(this, Invocation.method(#get, [userId])),
            ),
          )
          as _i5.Future<_i2.UserSettings>);

  @override
  _i5.Future<void> setDefaultCurrency(
    String? userId,
    _i6.SupportedCurrency? currency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultCurrency, [userId, currency]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setBillingCycle(String? userId, _i7.BillingCycle? cycle) =>
      (super.noSuchMethod(
            Invocation.method(#setBillingCycle, [userId, cycle]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markCurrencyMigrated(
    String? userId, {
    required int? migrated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markCurrencyMigrated,
              [userId],
              {#migrated: migrated},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setProfession(String? userId, String? profession) =>
      (super.noSuchMethod(
            Invocation.method(#setProfession, [userId, profession]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markSetupCompleted(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markSetupCompleted, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markSetupSkipped(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markSetupSkipped, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markOnboardingStep(String? userId, String? step) =>
      (super.noSuchMethod(
            Invocation.method(#markOnboardingStep, [userId, step]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetOnboardingForDebug(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#resetOnboardingForDebug, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [CurrencyMigrationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyMigrationRepository extends _i1.Mock
    implements _i8.CurrencyMigrationRepository {
  MockCurrencyMigrationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> backfillCurrency(
    String? userId,
    _i6.SupportedCurrency? currency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#backfillCurrency, [userId, currency]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [ServicesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicesRepository extends _i1.Mock
    implements _i9.ServicesRepository {
  MockServicesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i10.Service>> add(
    _i10.Service? service, [
    int? quantity = 1,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#add, [service, quantity]),
            returnValue: _i5.Future<List<_i10.Service>>.value(<_i10.Service>[]),
          )
          as _i5.Future<List<_i10.Service>>);

  @override
  _i5.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i10.Service>> get(
    String? userId,
    DateTime? startDate, [
    DateTime? endDate,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId, startDate, endDate]),
            returnValue: _i5.Future<List<_i10.Service>>.value(<_i10.Service>[]),
          )
          as _i5.Future<List<_i10.Service>>);

  @override
  _i5.Future<void> update(_i10.Service? service) =>
      (super.noSuchMethod(
            Invocation.method(#update, [service]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setReceivedAt(List<String>? ids, DateTime? receivedAt) =>
      (super.noSuchMethod(
            Invocation.method(#setReceivedAt, [ids, receivedAt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> count(String? userId, [String? typeId]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [userId, typeId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countCreatedSince(String? userId, DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#countCreatedSince, [userId, since]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [ServiceTypeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceTypeRepository extends _i1.Mock
    implements _i11.ServiceTypeRepository {
  MockServiceTypeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ServiceType> add(_i3.ServiceType? serviceType) =>
      (super.noSuchMethod(
            Invocation.method(#add, [serviceType]),
            returnValue: _i5.Future<_i3.ServiceType>.value(
              _FakeServiceType_1(this, Invocation.method(#add, [serviceType])),
            ),
          )
          as _i5.Future<_i3.ServiceType>);

  @override
  _i5.Future<List<_i3.ServiceType>> addAll(
    List<_i3.ServiceType>? serviceTypes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAll, [serviceTypes]),
            returnValue: _i5.Future<List<_i3.ServiceType>>.value(
              <_i3.ServiceType>[],
            ),
          )
          as _i5.Future<List<_i3.ServiceType>>);

  @override
  _i5.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ServiceType>> get(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId]),
            returnValue: _i5.Future<List<_i3.ServiceType>>.value(
              <_i3.ServiceType>[],
            ),
          )
          as _i5.Future<List<_i3.ServiceType>>);

  @override
  _i5.Future<void> update(_i3.ServiceType? serviceType) =>
      (super.noSuchMethod(
            Invocation.method(#update, [serviceType]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i12.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i13.AppUser? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i13.AppUser?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i5.Stream<_i13.AppUser?>.empty(),
          )
          as _i5.Stream<_i13.AppUser?>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i14.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> log(
    _i15.AnalyticsEvent? event, {
    Map<String, Object>? parameters = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#log, [event], {#parameters: parameters}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeService extends _i1.Mock implements _i16.TimeService {
  MockTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_2(this, Invocation.getter(#now)),
          )
          as DateTime);

  @override
  bool isRangeInLastMonth(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#isRangeInLastMonth, [start, end]),
            returnValue: false,
          )
          as bool);

  @override
  bool isRangeInThisMonth(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#isRangeInThisMonth, [start, end]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [InterstitialAdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterstitialAdService extends _i1.Mock
    implements _i17.InterstitialAdService {
  MockInterstitialAdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void preload() => super.noSuchMethod(
    Invocation.method(#preload, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> showIfAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#showIfAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
