// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-RnxUS1c9SSabauF-V4uNrdKBvDxfOA',
    appId: '1:207349852380:android:fa527d51f62aecef3dac19',
    messagingSenderId: '207349852380',
    projectId: 'kazi-clients-staging',
    storageBucket: 'kazi-clients-staging.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5lPrKxikonBW-ZwWrTildgFwHZ6Cm9E',
    appId: '1:207349852380:ios:2aa05164d9a093563dac19',
    messagingSenderId: '207349852380',
    projectId: 'kazi-clients-staging',
    storageBucket: 'kazi-clients-staging.firebasestorage.app',
    iosBundleId: 'com.myservices.kazi.staging',
    iosClientId: '207349852380-dqm4uu7gciaggfqd7mk3he2h38fpe5jc.apps.googleusercontent.com',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCXR4vD4NIKsBF4Vgu_MPX10c_e0bIb-PA",
    authDomain: "kazi-clients-staging.firebaseapp.com",
    projectId: "kazi-clients-staging",
    storageBucket: "kazi-clients-staging.firebasestorage.app",
    messagingSenderId: "207349852380",
    appId: "1:207349852380:web:9137937dba32ed3e3dac19",
    measurementId: "G-JSYPXSL323",
  );
}
