// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/clients/presenter/controllers/client_details_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kazi/features/auth/domain/models/app_user.dart' as _i7;
import 'package:kazi/features/auth/domain/services/auth_service.dart' as _i6;
import 'package:kazi/features/clients/domain/repositories/clients_repository.dart'
    as _i2;
import 'package:kazi_core/kazi_core.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ClientsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientsRepository extends _i1.Mock implements _i2.ClientsRepository {
  MockClientsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<({String id, _i4.ClientInfo info})>> getClients(
    String? ownerId, {
    int? limit = 10,
    String? startAfterName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClients,
              [ownerId],
              {#limit: limit, #startAfterName: startAfterName},
            ),
            returnValue:
                _i3.Future<List<({String id, _i4.ClientInfo info})>>.value(
                  <({String id, _i4.ClientInfo info})>[],
                ),
          )
          as _i3.Future<List<({String id, _i4.ClientInfo info})>>);

  @override
  _i3.Future<List<({String id, _i4.ClientInfo info})>> searchByName(
    String? ownerId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchByName, [ownerId, query]),
            returnValue:
                _i3.Future<List<({String id, _i4.ClientInfo info})>>.value(
                  <({String id, _i4.ClientInfo info})>[],
                ),
          )
          as _i3.Future<List<({String id, _i4.ClientInfo info})>>);

  @override
  _i3.Future<({String id, _i4.ClientInfo info})?> getClientDetails(
    String? ownerId,
    String? clientId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClientDetails,
              [ownerId, clientId],
              {#limit: limit},
            ),
            returnValue:
                _i3.Future<({String id, _i4.ClientInfo info})?>.value(),
          )
          as _i3.Future<({String id, _i4.ClientInfo info})?>);

  @override
  _i3.Future<List<_i4.ServiceHistoryItem>> getServiceHistory(
    String? ownerId,
    String? clientId, {
    int? limit,
    DateTime? startAfterDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getServiceHistory,
              [ownerId, clientId],
              {#limit: limit, #startAfterDate: startAfterDate},
            ),
            returnValue: _i3.Future<List<_i4.ServiceHistoryItem>>.value(
              <_i4.ServiceHistoryItem>[],
            ),
          )
          as _i3.Future<List<_i4.ServiceHistoryItem>>);

  @override
  _i3.Future<String> add(String? ownerId, _i4.User? client) =>
      (super.noSuchMethod(
            Invocation.method(#add, [ownerId, client]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#add, [ownerId, client]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<int> count(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#count, [ownerId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> update(String? clientId, _i4.User? client) =>
      (super.noSuchMethod(
            Invocation.method(#update, [clientId, client]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deactivate(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivate, [clientId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastService(
    String? clientId,
    String? serviceName,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastService, [
              clientId,
              serviceName,
              date,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i7.AppUser? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i7.AppUser?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i3.Stream<_i7.AppUser?>.empty(),
          )
          as _i3.Stream<_i7.AppUser?>);
}
