// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/clients/presenter/controllers/client_details_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kazi/features/auth/domain/models/app_user.dart' as _i8;
import 'package:kazi/features/auth/domain/services/auth_service.dart' as _i7;
import 'package:kazi/features/clients/domain/models/record_counters.dart'
    as _i4;
import 'package:kazi/features/clients/domain/repositories/clients_repository.dart'
    as _i2;
import 'package:kazi_core/kazi_core.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClientsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientsRepository extends _i1.Mock implements _i2.ClientsRepository {
  MockClientsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
    List<
      ({
        DateTime? archivedAt,
        _i4.RecordCounters counters,
        String id,
        _i5.ClientInfo info,
        String observation,
      })
    >
  >
  getClients(String? ownerId, {int? limit = 10, String? startAfterName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClients,
              [ownerId],
              {#limit: limit, #startAfterName: startAfterName},
            ),
            returnValue:
                _i3.Future<
                  List<
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >
                >.value(
                  <
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >[],
                ),
          )
          as _i3.Future<
            List<
              ({
                DateTime? archivedAt,
                _i4.RecordCounters counters,
                String id,
                _i5.ClientInfo info,
                String observation,
              })
            >
          >);

  @override
  _i3.Future<
    List<
      ({
        DateTime? archivedAt,
        _i4.RecordCounters counters,
        String id,
        _i5.ClientInfo info,
        String observation,
      })
    >
  >
  getArchivedClients(
    String? ownerId, {
    int? limit = 20,
    String? startAfterName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getArchivedClients,
              [ownerId],
              {#limit: limit, #startAfterName: startAfterName},
            ),
            returnValue:
                _i3.Future<
                  List<
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >
                >.value(
                  <
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >[],
                ),
          )
          as _i3.Future<
            List<
              ({
                DateTime? archivedAt,
                _i4.RecordCounters counters,
                String id,
                _i5.ClientInfo info,
                String observation,
              })
            >
          >);

  @override
  _i3.Future<
    List<
      ({
        DateTime? archivedAt,
        _i4.RecordCounters counters,
        String id,
        _i5.ClientInfo info,
        String observation,
      })
    >
  >
  getAllActiveClients(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllActiveClients, [ownerId]),
            returnValue:
                _i3.Future<
                  List<
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >
                >.value(
                  <
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >[],
                ),
          )
          as _i3.Future<
            List<
              ({
                DateTime? archivedAt,
                _i4.RecordCounters counters,
                String id,
                _i5.ClientInfo info,
                String observation,
              })
            >
          >);

  @override
  _i3.Future<
    List<
      ({
        DateTime? archivedAt,
        _i4.RecordCounters counters,
        String id,
        _i5.ClientInfo info,
        String observation,
      })
    >
  >
  searchByName(String? ownerId, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchByName, [ownerId, query]),
            returnValue:
                _i3.Future<
                  List<
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >
                >.value(
                  <
                    ({
                      DateTime? archivedAt,
                      _i4.RecordCounters counters,
                      String id,
                      _i5.ClientInfo info,
                      String observation,
                    })
                  >[],
                ),
          )
          as _i3.Future<
            List<
              ({
                DateTime? archivedAt,
                _i4.RecordCounters counters,
                String id,
                _i5.ClientInfo info,
                String observation,
              })
            >
          >);

  @override
  _i3.Future<
    ({
      DateTime? archivedAt,
      _i4.RecordCounters counters,
      String id,
      _i5.ClientInfo info,
      String observation,
    })?
  >
  findByIdentifier(String? ownerId, String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#findByIdentifier, [ownerId, identifier]),
            returnValue:
                _i3.Future<
                  ({
                    DateTime? archivedAt,
                    _i4.RecordCounters counters,
                    String id,
                    _i5.ClientInfo info,
                    String observation,
                  })?
                >.value(),
          )
          as _i3.Future<
            ({
              DateTime? archivedAt,
              _i4.RecordCounters counters,
              String id,
              _i5.ClientInfo info,
              String observation,
            })?
          >);

  @override
  _i3.Future<
    ({
      DateTime? archivedAt,
      _i4.RecordCounters counters,
      String id,
      _i5.ClientInfo info,
      String observation,
    })?
  >
  getClientDetails(String? ownerId, String? clientId, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClientDetails,
              [ownerId, clientId],
              {#limit: limit},
            ),
            returnValue:
                _i3.Future<
                  ({
                    DateTime? archivedAt,
                    _i4.RecordCounters counters,
                    String id,
                    _i5.ClientInfo info,
                    String observation,
                  })?
                >.value(),
          )
          as _i3.Future<
            ({
              DateTime? archivedAt,
              _i4.RecordCounters counters,
              String id,
              _i5.ClientInfo info,
              String observation,
            })?
          >);

  @override
  _i3.Future<List<_i5.ServiceHistoryItem>> getServiceHistory(
    String? ownerId,
    String? clientId, {
    int? limit,
    DateTime? startAfterDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getServiceHistory,
              [ownerId, clientId],
              {#limit: limit, #startAfterDate: startAfterDate},
            ),
            returnValue: _i3.Future<List<_i5.ServiceHistoryItem>>.value(
              <_i5.ServiceHistoryItem>[],
            ),
          )
          as _i3.Future<List<_i5.ServiceHistoryItem>>);

  @override
  _i3.Future<String> add(
    String? ownerId,
    _i5.User? client, {
    String? observation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #add,
              [ownerId, client],
              {#observation: observation},
            ),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #add,
                  [ownerId, client],
                  {#observation: observation},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<int> count(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#count, [ownerId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countActive(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#countActive, [ownerId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countArchived(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#countArchived, [ownerId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> countServicesOf(String? ownerId, String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#countServicesOf, [ownerId, clientId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> update(
    String? clientId,
    _i5.User? client, {
    String? observation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [clientId, client],
              {#observation: observation},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime> archive(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#archive, [clientId]),
            returnValue: _i3.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#archive, [clientId])),
            ),
          )
          as _i3.Future<DateTime>);

  @override
  _i3.Future<void> restore(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#restore, [clientId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [clientId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastService(
    String? clientId,
    String? serviceName,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastService, [
              clientId,
              serviceName,
              date,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i8.AppUser? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i8.AppUser?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i3.Stream<_i8.AppUser?>.empty(),
          )
          as _i3.Stream<_i8.AppUser?>);
}
