// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/app_update/presenter/controllers/app_update_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kazi/features/app_update/domain/models/app_update_info.dart'
    as _i2;
import 'package:kazi/features/app_update/domain/services/app_update_service.dart'
    as _i3;
import 'package:kazi_core/shared/services/local_storage/kazi_local_storage_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppUpdateInfo_0 extends _i1.SmartFake implements _i2.AppUpdateInfo {
  _FakeAppUpdateInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppUpdateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppUpdateService extends _i1.Mock implements _i3.AppUpdateService {
  MockAppUpdateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AppUpdateInfo> checkForUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#checkForUpdate, []),
            returnValue: _i4.Future<_i2.AppUpdateInfo>.value(
              _FakeAppUpdateInfo_0(
                this,
                Invocation.method(#checkForUpdate, []),
              ),
            ),
          )
          as _i4.Future<_i2.AppUpdateInfo>);
}

/// A class which mocks [KaziLocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKaziLocalStorageService extends _i1.Mock
    implements _i5.KaziLocalStorageService {
  MockKaziLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> write<T>(String? key, T? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<T?> read<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
