// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/services/presenter/controllers/service_landing_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kazi/features/auth/domain/models/app_user.dart' as _i8;
import 'package:kazi/features/auth/domain/services/auth_service.dart' as _i7;
import 'package:kazi/features/services/domain/models/catalog_item.dart' as _i2;
import 'package:kazi/features/services/domain/models/service.dart' as _i6;
import 'package:kazi/features/services/domain/repositories/catalog_item_repository.dart'
    as _i3;
import 'package:kazi/features/services/domain/repositories/services_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCatalogItem_0 extends _i1.SmartFake implements _i2.CatalogItem {
  _FakeCatalogItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatalogItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogItemRepository extends _i1.Mock
    implements _i3.CatalogItemRepository {
  MockCatalogItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CatalogItem> add(_i2.CatalogItem? catalogItem) =>
      (super.noSuchMethod(
            Invocation.method(#add, [catalogItem]),
            returnValue: _i4.Future<_i2.CatalogItem>.value(
              _FakeCatalogItem_0(this, Invocation.method(#add, [catalogItem])),
            ),
          )
          as _i4.Future<_i2.CatalogItem>);

  @override
  _i4.Future<List<_i2.CatalogItem>> addAll(
    List<_i2.CatalogItem>? catalogItems,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAll, [catalogItems]),
            returnValue: _i4.Future<List<_i2.CatalogItem>>.value(
              <_i2.CatalogItem>[],
            ),
          )
          as _i4.Future<List<_i2.CatalogItem>>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.CatalogItem>> get(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId]),
            returnValue: _i4.Future<List<_i2.CatalogItem>>.value(
              <_i2.CatalogItem>[],
            ),
          )
          as _i4.Future<List<_i2.CatalogItem>>);

  @override
  _i4.Future<void> update(_i2.CatalogItem? catalogItem) =>
      (super.noSuchMethod(
            Invocation.method(#update, [catalogItem]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ServicesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicesRepository extends _i1.Mock
    implements _i5.ServicesRepository {
  MockServicesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.Service>> add(
    _i6.Service? service, [
    int? quantity = 1,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#add, [service, quantity]),
            returnValue: _i4.Future<List<_i6.Service>>.value(<_i6.Service>[]),
          )
          as _i4.Future<List<_i6.Service>>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Service>> get(
    String? userId,
    DateTime? startDate, [
    DateTime? endDate,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<_i6.Service>>.value(<_i6.Service>[]),
          )
          as _i4.Future<List<_i6.Service>>);

  @override
  _i4.Future<void> update(_i6.Service? service) =>
      (super.noSuchMethod(
            Invocation.method(#update, [service]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setReceivedAt(List<String>? ids, DateTime? receivedAt) =>
      (super.noSuchMethod(
            Invocation.method(#setReceivedAt, [ids, receivedAt]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> count(String? userId, [String? catalogItemId]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [userId, catalogItemId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> countCreatedSince(String? userId, DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#countCreatedSince, [userId, since]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i8.AppUser? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i8.AppUser?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i4.Stream<_i8.AppUser?>.empty(),
          )
          as _i4.Stream<_i8.AppUser?>);
}
