// Mocks generated by Mockito 5.4.6 from annotations
// in kazi/test/lib/features/services/presenter/controllers/service_form_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kazi/features/auth/domain/models/app_user.dart' as _i11;
import 'package:kazi/features/auth/domain/services/auth_service.dart' as _i10;
import 'package:kazi/features/clients/domain/repositories/clients_repository.dart'
    as _i7;
import 'package:kazi/features/services/domain/models/service.dart' as _i6;
import 'package:kazi/features/services/domain/models/service_type.dart' as _i2;
import 'package:kazi/features/services/domain/repositories/service_type_repository.dart'
    as _i3;
import 'package:kazi/features/services/domain/repositories/services_repository.dart'
    as _i5;
import 'package:kazi_core/kazi_core.dart' as _i8;
import 'package:kazi_core/shared/services/in_app_review/kazi_in_app_review_manager.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeServiceType_0 extends _i1.SmartFake implements _i2.ServiceType {
  _FakeServiceType_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServiceTypeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceTypeRepository extends _i1.Mock
    implements _i3.ServiceTypeRepository {
  MockServiceTypeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServiceType> add(_i2.ServiceType? serviceType) =>
      (super.noSuchMethod(
            Invocation.method(#add, [serviceType]),
            returnValue: _i4.Future<_i2.ServiceType>.value(
              _FakeServiceType_0(this, Invocation.method(#add, [serviceType])),
            ),
          )
          as _i4.Future<_i2.ServiceType>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ServiceType>> get(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId]),
            returnValue: _i4.Future<List<_i2.ServiceType>>.value(
              <_i2.ServiceType>[],
            ),
          )
          as _i4.Future<List<_i2.ServiceType>>);

  @override
  _i4.Future<void> update(_i2.ServiceType? serviceType) =>
      (super.noSuchMethod(
            Invocation.method(#update, [serviceType]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ServicesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicesRepository extends _i1.Mock
    implements _i5.ServicesRepository {
  MockServicesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.Service>> add(
    _i6.Service? service, [
    int? quantity = 1,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#add, [service, quantity]),
            returnValue: _i4.Future<List<_i6.Service>>.value(<_i6.Service>[]),
          )
          as _i4.Future<List<_i6.Service>>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Service>> get(
    String? userId,
    DateTime? startDate, [
    DateTime? endDate,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#get, [userId, startDate, endDate]),
            returnValue: _i4.Future<List<_i6.Service>>.value(<_i6.Service>[]),
          )
          as _i4.Future<List<_i6.Service>>);

  @override
  _i4.Future<void> update(_i6.Service? service) =>
      (super.noSuchMethod(
            Invocation.method(#update, [service]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setReceivedAt(List<String>? ids, DateTime? receivedAt) =>
      (super.noSuchMethod(
            Invocation.method(#setReceivedAt, [ids, receivedAt]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> count(String? userId, [String? typeId]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [userId, typeId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> countCreatedSince(String? userId, DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#countCreatedSince, [userId, since]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [ClientsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientsRepository extends _i1.Mock implements _i7.ClientsRepository {
  MockClientsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<({String id, _i8.ClientInfo info})>> getClients(
    String? ownerId, {
    int? limit = 10,
    String? startAfterName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClients,
              [ownerId],
              {#limit: limit, #startAfterName: startAfterName},
            ),
            returnValue:
                _i4.Future<List<({String id, _i8.ClientInfo info})>>.value(
                  <({String id, _i8.ClientInfo info})>[],
                ),
          )
          as _i4.Future<List<({String id, _i8.ClientInfo info})>>);

  @override
  _i4.Future<List<({String id, _i8.ClientInfo info})>> searchByName(
    String? ownerId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchByName, [ownerId, query]),
            returnValue:
                _i4.Future<List<({String id, _i8.ClientInfo info})>>.value(
                  <({String id, _i8.ClientInfo info})>[],
                ),
          )
          as _i4.Future<List<({String id, _i8.ClientInfo info})>>);

  @override
  _i4.Future<({String id, _i8.ClientInfo info})?> getClientDetails(
    String? ownerId,
    String? clientId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClientDetails,
              [ownerId, clientId],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<({String id, _i8.ClientInfo info})?>.value(),
          )
          as _i4.Future<({String id, _i8.ClientInfo info})?>);

  @override
  _i4.Future<List<_i8.ServiceHistoryItem>> getServiceHistory(
    String? ownerId,
    String? clientId, {
    int? limit,
    DateTime? startAfterDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getServiceHistory,
              [ownerId, clientId],
              {#limit: limit, #startAfterDate: startAfterDate},
            ),
            returnValue: _i4.Future<List<_i8.ServiceHistoryItem>>.value(
              <_i8.ServiceHistoryItem>[],
            ),
          )
          as _i4.Future<List<_i8.ServiceHistoryItem>>);

  @override
  _i4.Future<String> add(String? ownerId, _i8.User? client) =>
      (super.noSuchMethod(
            Invocation.method(#add, [ownerId, client]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#add, [ownerId, client]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<int> count(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#count, [ownerId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> update(String? clientId, _i8.User? client) =>
      (super.noSuchMethod(
            Invocation.method(#update, [clientId, client]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deactivate(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivate, [clientId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastService(
    String? clientId,
    String? serviceName,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastService, [
              clientId,
              serviceName,
              date,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i11.AppUser? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i11.AppUser?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i4.Stream<_i11.AppUser?>.empty(),
          )
          as _i4.Stream<_i11.AppUser?>);
}

/// A class which mocks [KaziInAppReviewManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockKaziInAppReviewManager extends _i1.Mock
    implements _i12.KaziInAppReviewManager {
  MockKaziInAppReviewManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> onAppStarted() =>
      (super.noSuchMethod(
            Invocation.method(#onAppStarted, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onServiceCreated() =>
      (super.noSuchMethod(
            Invocation.method(#onServiceCreated, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
